version: 2

project_name: migrate

release:
  prerelease: auto

builds:
  - skip: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files: [ LICENSE, README.md ]

changelog:
  use: github-native
